container: {type: ColumnPanel}
components:
- name: btn_del
  properties: {text: '', icon: 'fa:remove', role: filled-button, icon_align: right}
  type: Button
  layout_properties: {grid_position: 'IGRRSZ,WJBSTF'}
  data_bindings:
  - {property: text, code: 'self.item[''first_name''] + '' '' + self.item[''last_name''] + '' ('' + self.item[''email''] + '')''', writeback: false}
  - {property: enabled, code: 'self.user[''auth_members'']', writeback: false}
  event_bindings: {click: btn_del_click}
is_package: true
