is_package: true
container: {type: ColumnPanel}
components:
- name: cp_volrole
  properties: {role: tonal-card, col_widths: '{"AGWNQU":10,"VMKXPK":50,"OXIQSY":10,"BXXRXF":50,"LXDZPR":10,"LEOVPD":50,"MGLQRF":10,"GOOLMB":50}'}
  type: ColumnPanel
  layout_properties: {grid_position: 'RSIOSV,AQNTFT'}
  components:
  - name: lbl_name
    properties: {align: right, text: Name}
    type: Label
    layout_properties: {grid_position: 'TBKGML,AGWNQU'}
  - name: tb_name
    properties: {role: outlined}
    type: TextBox
    layout_properties: {grid_position: 'TBKGML,VMKXPK'}
    data_bindings:
    - {property: enabled, code: 'self.user[''auth_members'']', writeback: false}
    - {property: text, code: 'self.item[''name'']', writeback: false}
    event_bindings: {lost_focus: update_role, pressed_enter: update_role}
  - name: lbl_reports_to
    properties: {align: right, text: Reports To}
    type: Label
    layout_properties: {grid_position: 'CJSCQM,OXIQSY'}
  - name: tb_reports_to
    properties: {role: outlined}
    type: TextBox
    layout_properties: {grid_position: 'CJSCQM,BXXRXF'}
    data_bindings:
    - {property: enabled, code: 'self.user[''auth_members'']', writeback: false}
    - {property: text, code: 'self.item[''reports_to'']', writeback: false}
    event_bindings: {lost_focus: update_role, pressed_enter: update_role}
  - name: lbl_assigned
    properties: {align: right, text: Assigned To}
    type: Label
    layout_properties: {grid_position: 'PTCRDA,LXDZPR'}
  - name: outlined_card_1
    properties: {role: outlined-card, background: 'theme:Surface Variant'}
    type: ColumnPanel
    layout_properties: {grid_position: 'PTCRDA,LEOVPD'}
    components:
    - name: fp_assigned_to
      properties: {border: '', background: ''}
      type: FlowPanel
      layout_properties: {grid_position: 'EVWQNT,JMVSUT'}
  - name: lbl_assign
    properties: {align: right, text: Assign to Members}
    type: Label
    layout_properties: {grid_position: 'ILFTKC,MGLQRF'}
  - name: dd_addmember
    properties: {role: outlined, placeholder: None, include_placeholder: true}
    type: DropDown
    layout_properties: {grid_position: 'ILFTKC,GOOLMB'}
    data_bindings: []
    event_bindings: {change: dd_addmember_change}
  - name: lbl_last_update
    properties: {}
    type: Label
    layout_properties: {grid_position: 'JVYIXD,ZEOQZG'}
    data_bindings: []
  - name: btn_guide
    properties: {text: View Guide, role: outlined-button, align: right}
    type: Button
    layout_properties: {grid_position: 'SVRNIZ,TLYENX'}
    event_bindings: {click: btn_guide_click}
  - name: fl_handbook
    properties: {text: Upload/Replace Guide PDF, role: outlined-button, align: right}
    type: FileLoader
    layout_properties: {grid_position: 'MHQKDW,FDQJID'}
    data_bindings:
    - {property: visible, code: 'self.user[''auth_members'']', writeback: false}
    event_bindings: {change: fl_handbook_change}
