container: {type: ColumnPanel}
components:
- name: dg_roles
  properties:
    columns:
    - {id: JKSDUP, title: Name, data_key: name}
    - {id: VJQQOR, title: Last Edit, data_key: last_update}
    - {id: OJLQEN, title: Actions, data_key: column_3}
    show_page_controls: false
    rows_per_page: 0
  type: DataGrid
  components:
  - name: rp_roles
    properties: {item_template: Roles.RoleRow}
    type: RepeatingPanel
  layout_properties: {grid_position: 'PSLCFY,GQWGSN'}
- name: btn_add
  properties: {text: Add Volunteer Role, role: outlined-button, icon: 'fa:plus', align: right}
  type: Button
  layout_properties: {grid_position: 'RORZZY,GSTJEX'}
  event_bindings: {click: btn_add_click}
  data_bindings:
  - {property: visible, code: 'self.user[''auth_members'']', writeback: false}
- name: cp_addrole
  properties: {role: outlined-card, col_widths: '{"JGULMP":10,"XFXLWU":50,"FNHBRL":10}', visible: false}
  type: ColumnPanel
  layout_properties: {grid_position: 'UIHRYA,VUHSJM'}
  components:
  - name: lbl_new_role
    properties: {align: right, text: Name}
    type: Label
    layout_properties: {grid_position: 'BYOHPT,JGULMP'}
  - name: tb_new_role
    properties: {role: outlined}
    type: TextBox
    layout_properties: {grid_position: 'BYOHPT,XFXLWU'}
  - name: btn_save_new_role
    properties: {text: Save New Role, role: filled-button}
    type: Button
    layout_properties: {grid_position: 'ASUKQT,CRCIBX'}
    event_bindings: {click: btn_save_new_role_click}
is_package: true
