components:
- components:
  - name: rp_roles
    properties: {item_template: Roles.RoleRow}
    type: RepeatingPanel
  layout_properties: {grid_position: 'PSLCFY,GQWGSN'}
  name: dg_roles
  properties:
    columns:
    - {data_key: name, id: JKSDUP, title: Name}
    - {data_key: last_update, id: VJQQOR, title: Last Edit}
    - {data_key: column_3, id: OJLQEN, title: Actions}
    rows_per_page: 0
    show_page_controls: false
  type: DataGrid
- data_bindings: []
  event_bindings: {click: btn_add_click}
  layout_properties: {grid_position: 'QQRBLC,CHJWDZ'}
  name: btn_add
  properties: {align: center, icon: 'fa:plus', role: filled-button, text: Add Role}
  type: Button
- components:
  - layout_properties: {grid_position: 'BYOHPT,JGULMP'}
    name: lbl_new_role
    properties: {align: right, text: Name}
    type: Label
  - layout_properties: {grid_position: 'BYOHPT,XFXLWU'}
    name: tb_new_role
    properties: {role: outlined}
    type: TextBox
  - layout_properties: {grid_position: 'IWCKSX,VFWGEZ'}
    name: lbl_permissions
    properties: {text: Permissions}
    type: Label
  - layout_properties: {grid_position: 'IWCKSX,LVGDBF'}
    name: msdd_permissions
    properties: {}
    type: form:dep_dmhomulhrajp9w:MultiSelectDropDown
  - event_bindings: {click: btn_save_new_role_click}
    layout_properties: {grid_position: 'ASUKQT,CRCIBX'}
    name: btn_save_new_role
    properties: {role: filled-button, text: Save New Role}
    type: Button
  layout_properties: {grid_position: 'UIHRYA,VUHSJM'}
  name: cp_addrole
  properties: {col_widths: '{"JGULMP":10,"XFXLWU":50,"VFWGEZ":10,"LVGDBF":50}', role: outlined-card, visible: false}
  type: ColumnPanel
container:
  event_bindings: {show: form_show}
  type: ColumnPanel
is_package: true
